# params
record_start_time: '2016050510'
record_end_time: '2019050513'
exist_record_time: '2018050513'


# set model
model_params:
    # variable params
    target_columns: ['pm25', 'pm10', 'so2', 'co', 'no2', 'o3']
    selected_columns: ['temp', 'sd', 'ws', 'pm10', 'pm25', 'co', 'no2', 'o3', 'so2', 'wd', 'weather', 'clock_num', 'weekday', 'month']
    continuous_columns: ['temp', 'sd', 'ws', 'pm10', 'pm25', 'co', 'no2', 'o3', 'so2']
    discrete_columns: ['wd', 'weather', 'clock_num', 'weekday', 'month']
    variable_bounds:
        pm25: [0, 500]
        temp: [-20, 40]
        sd: [0, 110]
        ws: [0, 10]
        pm10: [0, 800]
        co: [0, 7]
        no2: [0, 200]
        o3: [0, 350]
        so2: [0, 500]

    # defined params
    samples_len: 15000
    pred_horizon_len: 8500
    pred_dim: 24

    # model training params
    lr: 0.0001
    epochs: 60000
    batch_size: 3000

    embed_lags:  # corresponding to acf decreasing to 0.9
        pm25: 1
        temp: 1
        sd: 1
        ws: 1
        pm10: 1
        co: 1
        no2: 1
        o3: 1
        so2: 1

    acf_lags:
        pm25: 52
        temp: 10
        sd: 8
        ws: 30
        pm10: 54
        co: 48
        no2: 52
        o3: 10
        so2: 70

    discrete_embed_lags:
        wd: 1
        weather: 1
        clock_num: 1
        weekday: 1
        month: 1

    discrete_acf_lags:
        wd: 24
        weather: 24
        clock_num: 1
        weekday: 1
        month: 1



