# params
record_start_time: '2016050510'
record_end_time: '2019050513'
exist_record_time: '2018050513'


# set model
model_params:
    # variable params
    target_columns: ['pm25', 'pm10', 'so2', 'co', 'no2', 'o3']
    selected_columns: ['temp', 'sd', 'ws', 'pm10', 'pm25', 'co', 'no2', 'o3', 'so2', 'wd', 'weather', 'clock_num', 'weekday', 'month']
    continuous_columns: ['temp', 'sd', 'ws', 'pm10', 'pm25', 'co', 'no2', 'o3', 'so2']
    discrete_columns: ['wd', 'weather', 'clock_num', 'weekday', 'month']
    variable_bounds:
        pm25: [0, 500]
        temp: [-20, 40]
        sd: [0, 110]
        ws: [0, 10]
        pm10: [0, 800]
        co: [0, 7]
        no2: [0, 200]
        o3: [0, 350]
        so2: [0, 500]

    # defined params
    samples_len: 15000
    pred_horizon_len: 8500
    pred_dim: 72

    # model training params
    lr: 0.001
    epochs: 400000
    batch_size: 3000

    embed_lags:  # corresponding to acf decreasing to 0.6
#        pm25: 5
#        temp: 4
#        sd: 4
#        ws: 3
#        pm10: 6
#        co: 4
#        no2: 4
#        o3: 3
#        so2: 4
        pm25: 4
        temp: 3
        sd: 3
        ws: 2
        pm10: 4
        co: 3
        no2: 3
        o3: 2
        so2: 3

    acf_lags:
        pm25: 78
        temp: 10
        sd: 10
        ws: 13
        pm10: 80
        co: 78
        no2: 33
        o3: 8
        so2: 78
